POST http://localhost:3003/Participation/insert
Content-Type: application/json

{
    "firstName": "Robervaldo",
    "lastName": "silva",
    "participation": "74"
}

###

GET http://localhost:3003/participation/select

###

PUT http://localhost:3003/participation/update
Content-Type: application/json

{
    "id":"7d4e7134-37b8-427b-83ce-94435469431d",
    "firstName": "Davi",
    "lastName": "Araujo",
    "participation": 95
}

###

DELETE http://localhost:3003/participation/delete
Content-Type: application/json

{
    "firstName": "Davi",
    "lastName": "Araujo"
}
